### ISSUE TITLE
Integrate EPaper Functionality

### ISSUE THREAD

**Issue by ancor1369** [ancor1369/EmbeddedIOTProject#11]
Start the research on the integration of the EPaper so that it is possible to create the images out of the information we are going to receiver over the RF interface.

**Comment by gurwinder13** [comment]
ok

**Comment by ancor1369** [comment]
The integration of the module is done. It is now a reality and it is possible to continue to make more work on the the display of actual information.

The initialization process is now in place and ready to be further implemented with more functionality.
