### ISSUE TITLE
Complement Product

### ISSUE THREAD

**Issue by ancor1369** [ancor1369/EmbeddedIOTProject#33]
Hi @gurwinder13,

I need your help building an extra API.

Name of endpoint: 

/label

Verbs:

Get, Get/ID, Post, Patch

Object to use:

```json

{
      "LabelNumber":"1",
      "LableName":"This is the name of the label"
}
```

Please a new model in the mongoDB database and the information.

Let me know if you have any questions

Please in Get, make sure to return the whole listing and Get/Id filtered by the ID provided which will be the LabelNumber

**Comment by gurwinder13** [comment]
created label model for different labels.
