### ISSUE TITLE
Product Label API

### ISSUE THREAD

**Issue by ancor1369** [ancor1369/EmbeddedIOTProject#34]
Hi @gurwinder13,

Can you please help me with the following task:

We need to create a new entity in the mongoDB and the corresponding Rest calls.

This new entity will hold the information of what products go with what Labels. We are making higher level relations that is controlled by the end user directly, not the back end you are building.

Name of EndPoint:

/labelproduct

Verbs:

Get, Get/ID, Post, Patch

Object:

```json
{
   "LabelNumber":"5",
    "ProductSKU":"8546554"
}
```

Please in Get, make sure to return the whole listing and Get/Id filtered by the ID provided which will be the ProductSKU

**Comment by gurwinder13** [comment]
created label product object
