### ISSUE TITLE
Capture Serial data on a C++ program

### ISSUE THREAD

**Issue by ancor1369** [ancor1369/EmbeddedIOTProject#35]
Hi @puneetkpopli 

Please create a simple program that compiles and runs that interfaces to the serial interface of the Beagle board. The data that arrives over the serial interface needs to be printed on the output of the program when executing it.

To complete this mini project, you will need to do the following:

1. Create a program on Arduino to send data over serial interface continuously. You can follow the next tutorial.

https://create.arduino.cc/projecthub/SandroMesquita/function-serial-print-in-only-one-line-29ef8d?ref=tag&ref_id=serial&offset=0

2. After you validate that you are receiving the serial data on your windows machine connected to your Arduino, You will make the next set up:

![image](https://user-images.githubusercontent.com/25968721/78501838-a85a2300-772b-11ea-9f34-ddddf9be6f15.png)

The Arduino will start sending data over serial interface to your beagle board, You will connect your beagle board to the computer over USB and you will interact with the Beagle board over TCP/IP by using an SSH client called SmarTTY.

https://sysprogs.com/SmarTTY/download/

3. To develop your C++ program on Linux, you will configure Netbeans 8.1 to develop remotely. You are going to write your code on your Windows machine, but you will compile and run your code on Linux ion your Beagle Board. Please follow this instructions:

https://netbeans.org/kb/docs/cnd/remotedev-tutorial.html

Note: For this task, there is another option which is to set up a cross tool chain such as Linaro or another one. But this path requires you to have a Linux host machine to work which you do not have, so we will do it over this method.

If you have any questions, please let me know.

**Comment by ancor1369** [comment]
Here a couple of resources on how to get data on a serial interface on Linux:

https://en.wikibooks.org/wiki/Serial_Programming/Serial_Linux

https://blog.mbedded.ninja/programming/operating-systems/linux/linux-serial-ports-using-c-cpp/

**Comment by puneetkpopli** [comment]
serial data transfer using arduino is resolved

**Comment by puneetkpopli** [comment]
the remaining part is on its way

**Comment by ancor1369** [comment]
Hi, please keep this issue open until it is completed.
