### ISSUE TITLE
Crteate a Dynamic table using Java Script and the API

### ISSUE THREAD

**Issue by ancor1369** [ancor1369/EmbeddedIOTProject#36]
Hi @manpreet730931 

# To Be done

Create a dynamic table that as soon as the HTML page loads in the browser, makes an API call to the API server and use the response information to paint the table.

# Resources

Please, use the following API call from Java Scrip.

http://localhost:7000/product <- GET

![image](https://user-images.githubusercontent.com/25968721/78568266-d86afa00-77ef-11ea-803f-7ab5ab089249.png)

Once you get the answer object coming form the API, use it to create a dynamic table by using JavaScript To paint all the data that is coming from the it.

![image](https://user-images.githubusercontent.com/25968721/78568531-3c8dbe00-77f0-11ea-9df3-238f5a9b45c4.png)

# Hint to make your implementation

This tutorial shows how to create a dynamic table in Java Script.

https://www.aspsnippets.com/Articles/Create-dynamic-Table-in-HTML-at-runtime-using-JavaScript.aspx

![image](https://user-images.githubusercontent.com/25968721/78568735-89719480-77f0-11ea-98b3-adc8f4a709c2.png)

Here is an example on how to include a java script file on a HTML file and in a project

http://web.simmons.edu/~grabiner/comm244/weeknine/including-javascript.html

![image](https://user-images.githubusercontent.com/25968721/78568945-da818880-77f0-11ea-93bf-a59469881403.png)

**Comment by manpreet730931** [comment]
Dynamic table is done with javascript and it can work properly with all the three operations namely
1. creating product.
In this  we can easily change the parameters associated with them.
2. editing the product.
3. performing the pathc operations on product.
4. Listing the product.

**Comment by manpreet730931** [comment]
@ancor1369 
Please merge my branch website with the master.
